import Head from "next/head";

import type { AppProps } from "next/app";
import { ThemeProvider } from "styled-components";
import GlobalSyle from "utils/GlobalStyle";
import { theme } from "utils/theme";

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ThemeProvider theme={theme}>
        <>
          <GlobalSyle />
          <Component {...pageProps} />
        </>
      </ThemeProvider>
    </>
  );
}
export default MyApp;
